services:
  raw:
    build: 
      context: .
      dockerfile: ./raw_consumer/Dockerfile.raw
    volumes:
      - ./data/input:/app/input
      - ./data/raw_consumer:/app/output
      - ./raw_consumer/log:/app/log
    command: /app/entrypoint.sh
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - LOG_DIR=/app/log
      - PIPELINE_STAGE=RAW

  preprocessing:
    build: 
      context: .
      dockerfile: ./preprocessing/Dockerfile.preprocessing
    volumes:
      - ./data/raw_consumer:/app/input
      - ./data/preprocessing:/app/output
      - ./preprocessing/log:/app/log
    command: /app/entrypoint.sh
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - LOG_DIR=/app/log
      - PIPELINE_STAGE=PRE
    depends_on:
      - raw

  monitor:
    build: 
      context: ./monitor
      dockerfile: Dockerfile.monitor
    ports:
      - "8050:8050"
    volumes:
      - ./data/preprocessing:/app/input
      - ./raw_consumer/log:/app/logs/raw
      - ./preprocessing/log:/app/logs/preprocessing
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - PP_OUTPUT_DIR=/app/pp_output
      - LOG_DIR=/app/logs
    command: python3 /app/monitor.py
    depends_on:
      - raw
      - preprocessing

  infer:
    build: 
      context: .
      dockerfile: ./inference/Dockerfile.infer
    volumes:
      - ./data/preprocessing:/app/input
      - ./data/inference:/app/output
      - ./inference/log:/app/log
    command: /app/entrypoint.sh
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - LOG_DIR=/app/log
      - PIPELINE_STAGE=INFER
      - ARCH=vit_tiny
      - PATCH_SZ=16
      - DOWNSAMPLE_SIZE=5000
    depends_on:
      - preprocessing

volumes:
  data:
    driver: local


