FROM python:3.11.6 

WORKDIR /app

COPY ./segmentation/requirements.txt .

RUN pip install watchdog
RUN pip install -r requirements.txt

COPY ./entrypoint.sh .
COPY ./segmentation/segmentation.py ./main.py
COPY ./watchdog.py ./stat.py


ENTRYPOINT [ "/app/entrypoint.sh" ]